FROM php:8.2-fpm-alpine

RUN apk add --no-cache \
    postgresql-dev \
    && docker-php-ext-install \
    pdo_pgsql \
    pgsql

COPY php.ini /usr/local/etc/php/conf.d/app.ini

WORKDIR /var/www/html

CMD ["php-fpm"]
